{% set name = "znflow" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/znflow-{{ version }}.tar.gz
  sha256: 04cea6d52983824888ca6b441aabd686dd88900be69dcb372045e6ae401ac21b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - networkx >=3.0.0,<4.0.0
  run_constrained:
    - dask-core >=2024.0.0,<2025.0.0
    - distributed >=2024.0.0,<2025.0.0

test:
  imports:
    - znflow
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: A general purpose framework for building and running computational graphs.
  home: https://github.com/zincware/ZnFlow
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
