{% set name = "znflow" %}
{% set version = "0.2.7" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/znflow-{{ version }}.tar.gz
  sha256: 12f3584c6ba93250e93e2e63b7d600cc68bb39b6dd19e0f605a7430118863d91

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - networkx >=3.4.2
  run_constrained:
    - dask-core >=2024.0.0,<2025.0.0
    - distributed >=2024.0.0,<2025.0.0

test:
  imports:
    - znflow
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: A general purpose framework for building and running computational graphs.
  home: https://github.com/zincware/ZnFlow
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
